app_login:
    path: /login
    controller: App\Controller\LoginController::login
    methods: [GET, POST]

app_logout:
    path: /logout
    controller: App\Controller\LoginController::logout
    methods: [GET]

test_s3:
    path: /test
    controller: App\Controller\LoginController::testS3

dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index